### ISSUE TITLE
Numrow version

### ISSUE THREAD

**Issue by maximilienGilet** [skarrmann/horizon#2]
Hi, I really like this keyboard design (especially the ultra-thin double pcb idea) but I would LOVE a numrow version.

Do you plan to do one ? 

Thanks in advance

**Comment by Gauvainb** [comment]
I second this. A numwow variant would make it a killer.

**Comment by skarrmann** [comment]
Thank you both for your interest!

I have considered making a 5-row version of the Horizon. I will look into it this weekend.

With the additional row, there are two layout options for the center keys:

```
A. 64 keys (4 center keys)
oooooo  oooooo
oooooo  oooooo
oooooo  oooooo
oooooooooooooo
oooooooooooooo

B. 66 keys (6 center keys)
oooooo  oooooo
oooooo  oooooo
oooooooooooooo
oooooooooooooo
oooooooooooooo
```

I prefer option B. Do you have a preference?

**Comment by Gauvainb** [comment]
Hi @skarrmann, thanks for your swift reply ! 
I'd opt for option B as well, but only speaking for myself here.

**Comment by maximilienGilet** [comment]
Thanks for the quick reply ! 

I would also prefer option B even if the Horizon64 name would be epic haha

Do you think option A would allow a tiny battery for a BLE board ?

**Comment by skarrmann** [comment]
Great, thanks for your replies @Gauvainb and @maximilienGilet.I'll start with the 66 key approach then.

@maximilienGilet With the 64 key option, the extra space would allow for a larger LiPo battery. However, the 301230 size (3.0mm height x 12mm width x 30mm length) LiPo battery would work for the 66 layout key too! [Here's a photo showing this battery under a nice!nano](https://photos.app.goo.gl/HzBFCZwWxUVowQeq8).

**Comment by skarrmann** [comment]
The the 5-row version of Horizon is almost done! Introducing Morizon: https://github.com/skarrmann/morizon

The PCB designs for both MX and Choc versions are complete. And the QMK firmware should be all set too.

I plan on reviewing the PCBs one more time just to make sure everything is correct. And then later in the week, I will probably submit one of the boards to JLCPCB for printing (most likely the MX version - I have some spare switches to use).

@maximilienGilet @Gauvainb If you have a chance, could you please check the Morizon repository and see if the PCB and Gerber files look good to you? Thank you!

**Comment by maximilienGilet** [comment]
Epic ! 

Sadly I know nothing about pcb design so I will only help with build photos

If the rev1 is working as intended I will order a choc version and build one with a nice!nano and battery 

Thank you for the quick responses

**Comment by Gauvainb** [comment]
> 

Brilliant, I will have a look hoping my very limited PCB design skills can help !
Thanks for your work !

**Comment by skarrmann** [comment]
I finished my review of the PCBs, and everything looks correct. @Gauvainb Thank you for taking a look, and let me know if you notice any issues!

Tomorrow night (unless an issue is found), I will submit the MX Morizon PCBs to JLCPCB for printing.

**Comment by skarrmann** [comment]
[MX Morizon PCBs have been ordered from JLCPCB](https://i.imgur.com/1l9SuLv.png).

JLCPCB approved the designs just a few minutes after ordering. There were no extra costs either :)

If you would like to order PCBs and are eager to build the keyboard, then I am fairly confident the design is ready for your use now. But if you want to be cautious, I will confirm how everything goes after I finish the keyboard build.

It will take about two weeks for the PCBs to arrive. I will let you know when I receive them.

**Comment by Gauvainb** [comment]
Excellent, thanks again for your work on this ! I tend to always be on the cautious side after letdowns with different designs...But this one being a derivative of the original horizon I see no reason why it wouldn't work.

Plan is to try and build a choc slim one with nice!nano and small battery for a fully BT work setup!

**Comment by skarrmann** [comment]
The Morizon MX PCBs arrived from JLCPCB today. They look great!

![IMG_20220302_124746332_HDR](https://user-images.githubusercontent.com/697412/156420005-8291b08d-c5b0-456c-b609-c57139d1187b.jpg)
![IMG_20220302_125014923_HDR](https://user-images.githubusercontent.com/697412/156420010-e820c227-ba64-4242-ad91-d7eeefa3fd23.jpg)


I will build it and test it by this weekend. I will keep you posted!

**Comment by maximilienGilet** [comment]
Looks so damn good !

Thank you for your dedication

**Comment by Gauvainb** [comment]
Can't wait to see the results !

**Comment by skarrmann** [comment]
The Morizon MX build is complete, and everything works perfectly with the QMK keyboard definition 😃.

Here are some photos of the finished product:

![IMG_20220305_175118336_HDR](https://user-images.githubusercontent.com/697412/156902782-f81d7c49-49e8-4542-add9-e6bc66b2757d.jpg)

![IMG_20220305_175350184_HDR](https://user-images.githubusercontent.com/697412/156902790-ff281858-308e-4c0a-a2a4-d0dd3dcf5d9a.jpg)

![IMG_20220305_175613418_HDR](https://user-images.githubusercontent.com/697412/156902796-ae5865a5-bcb8-4e57-8d34-720dd4ac74c8.jpg)

Tomorrow, I will submit the PR for the QMK firmware, and write an intro post on /r/olkb.

I would love to see your finished builds too. If you could take a photo of a complete Morizon Choc build and allow me to show it on the repo, I would greatly appreciate it.

Thank you both for your interest!

**Comment by maximilienGilet** [comment]
Epic ! I will coordinate with @Gauvainb for Choc builds with a battery and a nice!nano

thanks a lot
